version: '3'
services:
  que-ui:
    image: que-ui
    entrypoint: /usr/local/bin/que-ui
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGDATABASE: postgres
    ports:
    - "8080:8080"
    - "8081:8081"
  postgres:
    image: postgres
  prepare-db:
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGDATABASE: postgres
    build: integration/prepare-db
  que:
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGDATABASE: postgres
      EKG_DATADIR: /opt/app/ekg
    build: integration/que

