resolver: lts-9.17

packages:
- .
extra-deps: []

flags: {}

docker:
  enable: false

image:
  container:
    base: "que-ui-base"
    name: "que-ui"
    add:
      "client/": "/opt/app/client"

extra-package-dbs: []

