resolver: lts-9.17

packages:
- .
extra-deps: []

flags: {}

extra-package-dbs: []

image:
  container:
    base: "fpco/ubuntu-with-libgmp:14.04"
    name: que-ui
    entrypoints:
      - que-ui

docker:
  enable: false
