resolver: lts-9.17

packages:
- .
extra-deps: []

flags: {}

extra-package-dbs: []

image:
  containers:
    - base: alpine
      name: que-ui
      executables:
      - que-ui
      entrypoints:
      - que-ui

docker:
  enable: false
